### ISSUE TITLE
New tag for package maintainers

### ISSUE THREAD

**Issue by ml-** [cyanomiko/dcnnt-py#10]
Hi,

could you push a git tag for 0.4.0? I'm packaging this app on the AUR ([aur.archlinux.org/packages/dcnnt](https://aur.archlinux.org/packages/dcnnt/)) and would appreciate a new tag so I can provide the package without pointing to commit hashes.

**Comment by cyanomiko** [comment]
Thanks for report! Done.
https://github.com/cyanomiko/dcnnt-py/releases/tag/0.4.0
