### ISSUE TITLE
dcnnt start dcnnt: command not found

### ISSUE THREAD

**Issue by herbertstew** [cyanomiko/dcnnt-py#11]
Hello, I'm trying to set up the dcnnt server on my computer and cannot get it to start after installing it.

**Output:**

```
user@computer:~$ pip3 --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

```
```
user@computer:~$ python3 --version
Python 3.8.5
```

```
user@computer:~$ pip3 show dcnnt
Name: dcnnt
Version: 0.4.0
Summary: UI-less tool to connect Android phone with desktop
Home-page: https://github.com/cyanomiko/dcnnt-py
Author: cyanomiko
Author-email: cyanomiko@protonmail.com
License: UNKNOWN
Location: /home/user/.local/lib/python3.8/site-packages
Requires: pycryptodome
Required-by: 
```

```
user@computer:~$ pip3 check dcnnt
No broken requirements found.
```

```
user@computer:~$ dcnnt start
dcnnt: command not found
```

**Computer information:**

> Release Linux Mint 20.1 Ulyssa 64-bit
Kernel Linux 5.4.0-67-generic x86_64
MATE 1.24.0

**Comment by cyanomiko** [comment]
@herbertstew , hello.

 Is file `/home/user/.local/bin/dcnnt` exists? 
Are directory `/home/user/.local/bin` in `$PATH` envvar?

**Comment by theAkito** [comment]
@herbertstew 

You need to add the location of the script to your `PATH`. Once that is done, you either need to manually export the changed `PATH` in your current shell, or you need to reload your shell for the change to take effect.

**Comment by herbertstew** [comment]
sorry i just saw this now and didn't know what a $PATH was back then. it works now!
