### ISSUE TITLE
Error message at install "ModuleNotFoundError ... 'no setuptools'"

### ISSUE THREAD

**Issue by LinuxJoeUser** [cyanomiko/dcnnt-py#15]
I'm on Linux Mint XFCE 20.

Following the instructions in READ.me

![dcnnt-readme](https://user-images.githubusercontent.com/23580979/125980644-3d19c1eb-e25b-41d3-be15-4137de02bf9c.png)

results in 

![dcnnt-fail-071621](https://user-images.githubusercontent.com/23580979/125981617-2d1a3b55-78b5-4160-acb4-728139d15a74.png)

Copy-pasting from README.md results in the error seen in the screenshot above:  `ModuleNotFoundError: No module named 'setuptools'`.

Am I missing a dependency? A Library? Or just doing something wrong?  I'm happy to provide whatever docs / logs / tests you may need.

**Comment by cyanomiko** [comment]
@LinuxJoeUser, probably your missing [setuptools](https://github.com/pypa/setuptools) library. Just do ` pip install setuptools` to fix it.
