### ISSUE TITLE
pypi serves 0.8.0 binary wheel

### ISSUE THREAD

**Issue by kurth4cker** [cyanomiko/dcnnt-py#21]
I installed dcnnt from pypi and it's version is 0.8.0. But no source package available. And this version not in github repository. Is it forgotten or wrongly published?

**Comment by cyanomiko** [comment]
@kurth4cker , forgot to push tag. Now fixed: [0.8.0](https://github.com/cyanomiko/dcnnt-py/tree/0.8.0). Thanks for report!
