### ISSUE TITLE
Cant set up on PC

### ISSUE THREAD

**Issue by shom13** [cyanomiko/dcnnt-py#4]
This is the error i get when installing on pc, following the guide. 

File "setup.py", line 1, in <module>
    import setuptools
ModuleNotFoundError: No module named 'setuptools'

**Comment by shom13** [comment]
Solved that, python was missing. But i have a few more questions. Now thay I have set it up, it runs when i type dcnnt start, but when i do dcnnt foreground, it starts but nothing else happens. 

How do i configure a folder in the pc where i can upload or download from to my phone, as there are no windows opening to set it up.

**Comment by cyanomiko** [comment]
There are not any GUI for server part of dcnnt. All configuring done via JSON files. 
You can found some information and examples here:
https://github.com/cyanomiko/dcnnt-py/blob/master/doc/config.md
https://github.com/cyanomiko/dcnnt-py/blob/master/doc/plugins.md

**Comment by shom13** [comment]
Well thank you for the reply. I tried to set it up, following the instructions, and i can see the server on my phone, but cannot upload or download. Cant figure out how to share the files

**Comment by cyanomiko** [comment]
What happens when you try to upload files? Are there any messages on phone?
Can you show content of configuration directory on PC and settings of phone app? Maybe passwords not set?

**Comment by shom13** [comment]
Well i will tell u in brief, i set it up following thw guide. Then i start it from the computer, then and i can see it from my phone. But then when i go to the upload tab, there is no device. I dont think im configuring it properly. I will try to share screenshots if i can

**Comment by shom13** [comment]
So i deleted all the previous files, started fresh install. At the end this is the error im getting 
![ff64134f-152c-4af5-b28b-2e18e56a87a0.png](https://user-images.githubusercontent.com/61466421/87859029-e92f1e00-c94f-11ea-811c-a3720b774d87.png)

**Comment by shom13** [comment]
Ok got past that, now i have started it on my pc, with dcnnt start

Sharing with you how my phone looks![Screenshot-2020-07-19-00-14-44.jpeg](https://user-images.githubusercontent.com/61466421/87859751-1d590d80-c955-11ea-8f37-5dcc4f993462.jpeg)

![Screenshot-2020-07-19-00-14-15.jpeg](https://user-images.githubusercontent.com/61466421/87859752-24801b80-c955-11ea-862f-2d91daf7cfab.jpeg)

**Comment by shom13** [comment]
![conf.json.png](https://user-images.githubusercontent.com/61466421/87860056-e6d0c200-c957-11ea-8252-6b623920e734.png)

![device.json.png](https://user-images.githubusercontent.com/61466421/87860059-eafcdf80-c957-11ea-8375-2f12e897d818.png)

**Comment by cyanomiko** [comment]
Seems like passwords not set properly. 

Steps to fix:
1. On PC. Check if password (entry `self.password`) set for you PC in file `~/.config/dcnnt/conf.json`. According to your screenshot it set to `password`.
2. On phone. Go to `Devices` -> `73 - HP-Notebook` -> `Password` and set password (`password`) from previous step. 
3. On phone. Go to `Settings`. Check if some value set in `Device password` entry. You can set your own value (e.g. `password2`) of course.
4. On PC. Set password (e.g. `password2`) from previous step to `password` entry in file `~/.config/dcnnt/devices/178429703.device.json`.
5. On PC. Restart dcnnt server: `dcnnt restart`.
6. On phone. Restart client app: `Exit` -> `Restart`.

**Comment by shom13** [comment]
Done that, edited the json file and entered the password in .config. Now it can see the device, but cannot upload file. Comes up with an error, device connect has stopped, e.a.a.i error connection timeout
![bc642a79-6042-42c7-8180-52e701377a9c.jpg](https://user-images.githubusercontent.com/61466421/87866511-494db080-c9a0-11ea-82c3-b0f88d85bda0.jpg)

**Comment by shom13** [comment]
Ok, after much trial, i was able to upload. It goes into temp/dconnect. But still cant figure out how to download a file from the computer. And is it possible to change the dconnect from /temp to some other location

**Comment by cyanomiko** [comment]
It is posible to change directory for uploaded files. In file `~/.config/dcnnt/plugins/file.conf.json` edit entry `download_directory`. This file also used to configure shared directories to download files to phone from PC. 
Configuration of file transmission plugin described with example here: [https://github.com/cyanomiko/dcnnt-py/blob/master/doc/plugins.md#file-transmission](https://github.com/cyanomiko/dcnnt-py/blob/master/doc/plugins.md#file-transmission).

**Comment by shom13** [comment]
Thank you so much for your patience with me. Its working now, was able to configure the download path. Thank you once again

**Comment by cyanomiko** [comment]
Ok. Then I close issue.
