### ISSUE TITLE
Connection Timed Out

### ISSUE THREAD

**Issue by joshuamoorexyz** [cyanomiko/dcnnt-py#7]
I have followed the inscructions rigidly and always get connection timed out as an error on the client side application.

Running Ubuntu 20.10

Installed using pip3

**Comment by chiraganand** [comment]
I am facing the same problem and the log tells me: `Incorrect password for device with UIN: 200600268`. I figured out that every time I do `dcnnt restart` the `password` field in device file gets replaced with `"password"` string.

**Comment by cyanomiko** [comment]
Which UIN and password set on phone and on PC side?

**Comment by cyanomiko** [comment]
Thanks @chiraganand, @joshuamoorexyz and @advortsov for report. Bug will be fixed in next release.
Temporary workaround:
1. `dcnnt stop`
2. Edit device JSON file.
3. `dcnnt start`
